name: talita
description: An Animated Movies app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  json_annotation: ^2.2.0
  intl: 0.16.1
  youtube_player_flutter: ^6.1.0+7
  flutter_staggered_grid_view: ^0.3.0
  url_launcher: ^5.4.5
  hive: ^1.4.1+1
  hive_flutter: ^0.2.1
  path_provider: ^1.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_model: ^0.0.2
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  hive_generator: ^0.5.2


flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
   - images/movie-placeholder.gif
   - images/imdb.png
   - images/cast_placeholder.png
   
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Bold.ttf
        - asset: fonts/ProductSans-Light.ttf
     
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Bold.ttf
        - asset: fonts/Ubuntu-Light.ttf
